baseURL = 'https://startup.stefanovskyi.com'
languageCode = 'en-us'
title = 'Startup Landing Page'
theme = 'agnes'

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "Oleksnadr Stefanovsky"
	google_analytics_id = "GA-"

		
[params.social]
	TwitterURL = "https://twitter.com/ostefanovskyi"
		
[params.content]
	LeadTitle = "Landing template for Startups"
	LeadDescription = "Our landing page template works for all the devices, so you only have to setup it once, and get beautiful results forever."
	ButtonCaption = "Pricing & Plans"
	ButtonURL = "http://google.com"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Feature 1"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Feature 2"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Feature 3"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Feature 4"
	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Starter"
	PricingRate = "27"	
	ButtonCaption = "Get Early Access"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"	

[[params.pricing]]
	PricingTitle = "Professional"
	PricingRate = "97"
	ButtonCaption = "Get Earlier Access"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"		
	
[[params.pricing]]
	PricingTitle = "Business"
	PricingRate = "147"
	ButtonCaption = "Get Earliest Access"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"	